# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# File: _config.yml
webrick:
  headers:
    My-Header: Rendra.design
    My-Other-Header: Web-dev-blogs

disqus:
  shortname: rendrap

google_analytics: UA-110544019-1

title: Rendra Blog
email: rendrapradana@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This blog is my way of sharing my thought and view about Web Design and Development.
  If you're interested in Rails, CSS, build tools, and productivity hack, then read along.
  You might find some usefull tips and trick along the way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rendra.design" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
paginate: 4
paginate_path: "/posts/page:num/"
# Build settings
markdown: kramdown
# theme: minima
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-paginate
permalink: pretty

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - package.json
  - node_modules/
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - resource/
  - README.md
  - .bundle
  - node_modules
  - assets/javascript/anchor-js
